publishdir = "public"
static = "/static"
builddrafts = false
baseurl = "https://digi-vub.github.io/getuigenissen/"
canonifyurls = true
theme = "hugo-academic-group"
title = "Getuigenissen"
math = true
copyright = "&copy; VUB, 2021"

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "https://digi.research.vub.be"
  author = "Jan Wijffels"
  email = "jan.wijffels@vub.be"
  address = "Vrije Universiteit Brussel, Pleinlaan 2, 1050 Brussels"
  slogan = "GETUIGENISSEN"
  slogan_text = "Zoek in Brugse politieverslagen uit de 18e-19e eeuw"

  [[params.slogan_columns]]
    title = "Overzicht Getuigenissen project"
    text =  "**Getuigenissen is een digitalisering- en transcriptieproject dat getuigenverklaringen en verhoren van verdachten uit 18de- en 19de-eeuwse criminele rechtbanken in BelgiÃ« verzamelt, digitaliseert en transcribeert. U kunt deze gedigitaliseerde gegevens bekijken en doorzoeken. Meer informatie vindt u [via deze link](/about)**"
    link = "/about"
    link_text = "lees verder"
    weight = 1
  
  [[params.slogan_columns]]
    title = "Zoek"
    text = "**U kunt deze 18e en 19e eeuws gegevens doorzoeken door woorden op te geven of te selecteren op bepaalde groepen van metadata die we verzameld hebben over elke getuigenis.  Zo kan u zoeken op naam, locatie, beroep, misdrijf, ... . Meer informatie vindt u [via deze link](/zoek)**"
    link = "/zoek"
    link_text = "lees verder"
    weight = 2


  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 0
    title = "Blog"
    subtitle = ""
    str_all = "Meer blogposts"
    str_read_more = "Lees"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Detail"
    subtitle = ""
    count = 2
    str_all = "Meer"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Project beschrijving"
      url = "/about"
      weight = 2

  [[menu.main]]
      name = "Zoek"
      url = "/zoek"
      weight = 3

    [[menu.main]]
      name = "Detail"
      url = "/#projects"
      weight = 4

  [[menu.main]]
      name = "Leden"
      url = "/#members"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "/#posts"
      weight = 6


  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 7
